name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DPX_BUILD_TESTS=ON -DPX_BUILD_EXAMPLES=ON -DPX_BUILD_TOOLS=ON
        cmake --build build
    - name: test
      run: |
        cd test
        ./../build/phoenix-tests -tse=messages,script,world -r=junit -o=report.xml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: 'tests/report.xml'
