name: Test

on: 
  push:
  pull_request:
  release:

jobs:
  test:
    name: 'Test'
    runs-on: 'ubuntu-latest'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake libasan6

          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 13
          
          ninja --version
          cmake --version
          clang++ --version
      - name: Configure
        shell: bash
        env:
          CC: '/usr/bin/clang'
          CXX: '/usr/bin/clang++'
        run: |
          mkdir target
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -G "Ninja" \
            -DCMAKE_INSTALL_PREFIX:PATH=target \
            -DPX_BUILD_EXAMPLES=ON
      - name: Build
        shell: bash
        run: cmake --build build
      - name: Test
        shell: bash
        run: |
          cd tests
          ./../build/phoenix-tests -tse=messages,script,world -r=junit -o=report.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'tests/report.xml'
